BescheLab/pontos_coleta/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^adicionar$', adicionar, name='adicionar'),
    url(r'^editar/(?P<pk>\d+)$', editar, name='editar'),
    url(r'^apagar/(?P<pk>\d+)$', apagar, name='apagar'),
    url(r'^listar$', listar, name='listar'),
    url(r'^selecionar/(?P<pk>\d+)$', selecionar, name='selecionar')
]

BescheLab/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^login', login, name='login'),
    url(r'^logout', logout_then_login, name='logout'),
    url(r'^table/', include('table.urls')),
    url(r'^pontos_coleta/', include('BescheLab.pontos_coleta.urls',
                                    namespace='pontos_coleta')),
    url(r'', include('BescheLab.layout.urls')),
    url(r'^pessoa/', include('BescheLab.pessoa.urls')),
    url(r'^financeiro/', include('BescheLab.financeiro.urls')),
    url(r'^laboratorio/', include('BescheLab.laboratorio.urls')),
]

BescheLab/pontos_coleta/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from auditlog.registry import auditlog


@python_2_unicode_compatible
class PontoColeta(models.Model):
    nome = models.CharField(max_length=50, unique=True)
    # Endereço
    logradouro = models.CharField(max_length=50, blank=True, null=True)
    numero = models.CharField('Número', max_length=10, blank=True, null=True)
    complemento = models.CharField(max_length=50, blank=True, null=True)
    bairro = models.CharField(max_length=50, blank=True, null=True)
    municipio = models.ForeignKey('pessoa.Municipio', null=True)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Ponto de coleta'
        default_permissions = []
        permissions = (
            ('change_pontocoleta', "Cadastrar"),
        )


auditlog.register(PontoColeta)

BescheLab/pontos_coleta/forms.py
from django import forms
from django_select2.forms import ModelSelect2Widget
from .models import PontoColeta
from ..pessoa.models import Municipio


class PontoColetaForm(forms.ModelForm):
    class Meta:
        model = PontoColeta
        fields = ('__all__')
        widgets = {
            'municipio': ModelSelect2Widget(
                model=Municipio, search_fields=['nome__icontains']),
        }

BescheLab/pontos_coleta/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required, permission_required
from .models import PontoColeta
from .forms import PontoColetaForm


@login_required
@permission_required('pontos_coleta.change_pontocoleta')
def listar(request):
    pontos = PontoColeta.objects.all()
    return render(request, 'pontos_coleta/listar.html',
                  {'pontos': pontos})


@login_required
@permission_required('pontos_coleta.change_pontocoleta')
def adicionar(request):
    if request.method == 'POST':
        form = PontoColetaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('pontos_coleta:listar'))
    else:
        form = PontoColetaForm()
    return render(request, 'pontos_coleta/form.html',
                  {'form': form})


@login_required
@permission_required('pontos_coleta.change_pontocoleta')
def editar(request, pk):
    ponto = PontoColeta.objects.get(pk=pk)
    if request.method == 'POST':
        form = PontoColetaForm(request.POST, instance=ponto)
        if form.is_valid():
            form.save()
            return redirect(reverse('pontos_coleta:listar'))
    else:
        form = PontoColetaForm(instance=ponto)
    return render(request, 'pontos_coleta/form.html',
                  {'form': form, 'object': ponto})


@login_required
@permission_required('pontos_coleta.change_pontocoleta')
def apagar(request, pk):
    if request.method == 'POST':
        ponto = PontoColeta.objects.get(pk=pk)
        ponto.delete()
    return redirect(reverse('pontos_coleta:listar'))


@login_required
def selecionar(request, pk):
    request.session['ponto_coleta_pk'] = pk
    return redirect(reverse('index'))

BescheLab/pontos_coleta/templates/pontos_coleta/form.html
{% extends 'layout-config.html' %}
{% load bootstrap3 %}
{% block conteudo %}
<div class="page-title">
    <div class="title_left">
        <h3>Ponto coleta</h3>
    </div>

</div>
<div class="clearfix"></div>

<div class="x_panel">
    <div class="x_title">
        <h2>{% if object %}Editar
            <small>
                Veja detalhes e/ou altere informações de um Ponto de Coleta.    
            </small>
            {% else %}Cadastrar
            <small>
                Adicione um novo Ponto de Coleta.
            </small>
            {% endif %}
        </h2>
        <div class="clearfix"></div>
    </div>
 
    <div class="x_content">
        <form novalidate class="form-horizontal form-label-left" method="POST">{% csrf_token %}
            {% bootstrap_form_errors form type='non_fields' %}
            {% bootstrap_field form.nome layout='horizontal' field_class='col-xs-12 col-sm-10 col-md-10' label_class='col-xs-12 col-sm-2 col-md-2' %}
            <div class="divider-dashed"></div>
            
            <div class="form-group">
                {% bootstrap_field form.logradouro field_class='col-xs-12 col-sm-4 col-md-4' label_class='col-xs-12 col-sm-2 col-md-2' form_group_class='' %}
                {% bootstrap_field form.numero field_class='col-xs-12 col-sm-4 col-md-4' label_class='col-xs-12 col-sm-2 col-md-2' form_group_class='' %}
            </div>
            
            <div class="form-group">
                {% bootstrap_field form.complemento field_class='col-xs-12 col-sm-4 col-md-4' label_class='col-xs-12 col-sm-2 col-md-2' form_group_class='' %}
                {% bootstrap_field form.bairro field_class='col-xs-12 col-sm-4 col-md-4' label_class='col-xs-12 col-sm-2 col-md-2' form_group_class='' %}
            </div>
            
            <div class="form-group">
                {% bootstrap_field form.municipio field_class='col-xs-12 col-sm-4 col-md-4' label_class='col-xs-12 col-sm-2 col-md-2' form_group_class='' %}
            </div>
            
            <div class="ln_solid"></div>
            
            <div class="form-group">
                <div class="col-md-10 col-md-offset-2">
                    {% if object %}
                    <div class="pull-right">
                        <button type="button" data-href="{% url 'pontos_coleta:apagar' object.pk %}" id="delete-link" class="btn btn-danger btn-sm">Excluir</button>
                    </div>
                    {% endif %}
                    <a href="{% url 'pontos_coleta:listar' %}" class="btn btn-primary btn-sm">Voltar</a>
                    <button type="submit" class="btn btn-success btn-sm">Salvar</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block extrascript %}
{% if object %}
{% with dialog_message='Deseja realmente excluir este ponto de coleta?' %}
{% include 'delete_dialog.html' %}
{% endwith %}
{% endif %}
{% endblock %}

BescheLab/pontos_coleta/templates/pontos_coleta/listar.html
{% extends 'layout-config.html' %}
{% block conteudo %}
<div class="page-title">
	<div class="title_left">
		<h3>Ponto de Coleta</h3>
	</div>
</div>

<div class="clearfix"></div>

<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>Lista 
					<small>
						Lista com todos os Pontos de Coleta. Clique numa linha para ver detalhes ou editar as 	informações.
					</small>
				</h2>
				<div class="clearfix"></div>
			</div>
			
			<div class="x_content">
				<br>
				<table id="datatable" class="table table-striped">
					<thead>
						<tr>
							<th>Nome</th>
						</tr>
					</thead>
					<tbody class="rowlink" data-link="row">
						{% for ponto in pontos %}
						<tr>
							<td><a href="{% url 'pontos_coleta:editar' ponto.pk %}">{{ ponto.nome }}</a></td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
{% endblock %}