BescheLab/layout/urls.py
from django.conf.urls import url
from .views import index, configuracoes, log


urlpatterns = [
    url(r'^log-acoes$', log.relatorio_acoes, name='relatorio_acoes'),
    url(r'^configuracoes$', configuracoes, name='configuracoes'),
    url(r'^$', index, name='index'),
]

BescheLab/pontos_coleta/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^adicionar$', adicionar, name='adicionar'),
    url(r'^editar/(?P<pk>\d+)$', editar, name='editar'),
    url(r'^apagar/(?P<pk>\d+)$', apagar, name='apagar'),
    url(r'^listar$', listar, name='listar'),
    url(r'^selecionar/(?P<pk>\d+)$', selecionar, name='selecionar')
]

BescheLab/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^login', login, name='login'),
    url(r'^logout', logout_then_login, name='logout'),
    url(r'^table/', include('table.urls')),
    url(r'^pontos_coleta/', include('BescheLab.pontos_coleta.urls',
                                    namespace='pontos_coleta')),
    url(r'', include('BescheLab.layout.urls')),
    url(r'^pessoa/', include('BescheLab.pessoa.urls')),
    url(r'^financeiro/', include('BescheLab.financeiro.urls')),
    url(r'^laboratorio/', include('BescheLab.laboratorio.urls')),
]

BescheLab/layout/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils import six


class ReadOnlyFieldsMixin(object):
    """Usage:

    class MyFormAllFieldsReadOnly(ReadOnlyFieldsMixin, forms.Form):
        ...

    class MyFormSelectedFieldsReadOnly(ReadOnlyFieldsMixin, forms.Form):
        readonly_fields = ('field1', 'field2')
        ...
    """
    readonly_fields = []

    def __init__(self, *args, **kwargs):
        readonly_fields = kwargs.pop('readonly_fields', None)
        if readonly_fields:
            self.readonly_fields = list(self.readonly_fields) + readonly_fields
        super(ReadOnlyFieldsMixin, self).__init__(*args, **kwargs)
        self.define_readonly_fields()

    def define_readonly_fields(self):
        fields = [field for field_name, field in six.iteritems(self.fields)
                  if field_name in self.readonly_fields]

        map(lambda field: self._set_readonly(field), fields)

    def _set_readonly(self, field):
        field.disabled = True

BescheLab/layout/views/log.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, permission_required
from auditlog.models import LogEntry


@login_required
@permission_required('pessoa.log_acoes', raise_exception=True)
def relatorio_acoes(request):
    log = LogEntry.objects.all()
    return render(request, 'relatorio-acoes.html', {'log': log})

BescheLab/layout/templates/alert-dialog.html
<div class="modal fade" id="alert-dialog" tabindex="-1" role="dialog" aria-labelledby="">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Aviso</h4>
            </div>
      
            <div class="modal-body">
                {{ dialog_message }}
            </div>
      
            <div class="modal-footer">
                <button type="button" class="btn btn-primary btn-sm" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>

BescheLab/layout/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <title>Besche Lab</title>

        <!-- JQuery -->
        <script src="{% static 'vendors/js/jquery.min.js' %}"></script>
        <!-- pace -->
        <script src="{% static 'vendors/js/pace/pace.min.js' %}"></script>
        <!-- Bootstrap -->
        <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
        <!-- NProgress -->
        <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
        <!-- iCheck -->
        <link href="{% static 'vendors/iCheck/skins/flat/green.css' %}" rel="stylesheet">
        <!-- bootstrap-progressbar -->
        <link href="{% static 'vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet">
        <!-- bootstrap-daterangepicker -->
        <link href="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.css' %}" rel="stylesheet">
        <link href="{% static 'vendors/switchery/dist/switchery.min.css' %}" rel="stylesheet">
        <link href="{% static 'vendors/switchery/dist/switchery.css' %}" rel="stylesheet">
        <!-- Custom Theme Style -->
        <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
        <!-- Select2 -->
        <link href="{% static 'vendors/select2/dist/css/select2.min.css' %}" rel="stylesheet">
        <!-- Switchery -->
        <link href="{% static 'vendors/switchery/dist/switchery.min.css' %}" rel="stylesheet">
        <!-- Tabela Responsiva -->
        <link href="{% static 'vendors/js/datatables/jquery.dataTables.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'vendors/js/datatables/buttons.bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'vendors/js/datatables/fixedHeader.bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'vendors/js/datatables/responsive.bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'vendors/js/datatables/scroller.bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        {{ form.media.css }}
        {% block extrahead %}{% endblock %}
    </head>

    <body style="background:#F7F7F7;">
        {% block conteudo %}{% endblock %}
        <!-- Bootstrap -->
        <script src="{% static 'vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
        <!-- FastClick -->
        <script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
        <!-- NProgress -->
        <script src="{% static 'vendors/nprogress/nprogress.js' %}"></script>
        <!-- bootstrap-progressbar -->
        <script src="{% static 'vendors/bootstrap-progressbar/bootstrap-progressbar.min.js' %}"></script>
        <!-- iCheck -->
        <script src="{% static 'vendors/iCheck/icheck.min.js' %}"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="{% static 'vendors/moment/min/moment.min.js' %}"></script>
        <script src="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
        <script src="{% static 'vendors/jquery.hotkeys/jquery.hotkeys.js' %}"></script>
        <script src="{% static 'vendors/google-code-prettify/src/prettify.js' %}"></script>
        <!-- Switchery -->
        <script src="{% static 'vendors/switchery/dist/switchery.min.js' %}"></script>
        <!-- Autosize -->
        <script src="{% static 'vendors/autosize/dist/autosize.min.js' %}"></script>

        <script src="{% static 'vendors/datatables.net/js/jquery.dataTables.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-scroller/js/dataTables.scroller.min.js' %}"></script>
        <!-- Custom Theme Scripts -->
        <script src="{% static 'build/js/custom.min.js' %}"></script>

        <!-- Autosize -->
        <script>
          $(document).ready(function() {
            autosize($('.resizable_textarea'));
          });
        </script>
        <!-- /Autosize -->
{{ form.media.js }}
{% block extrascript %}{% endblock %}
    </body>
</html>

BescheLab/layout/templates/configuracoes.html
{% extends 'layout-config.html' %}
{% block conteudo %}
<div class="page-title">
	<div class="title_left">
		<h3>Configurações</h3>
	</div>
</div>

<div class="clearfix"></div>

<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>Lista 
					<small>
						Configurações.
					</small>
				</h2>
				<div class="clearfix"></div>
			</div>

			<div class="x_content">
				<br>
			</div>
		</div>
	</div>
</div>
{% endblock%}

BescheLab/layout/templates/confirm-dialog.html
<div class="modal fade" id="confirm-dialog" tabindex="-1" role="dialog" aria-labelledby="">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Confirmar</h4>
            </div>
            <div class="modal-body" id="confirm-dialog-message">
                {{ dialog_message }}
            </div>
            <div class="modal-footer">
        	    <button type="button" id="confirm-dialog-no" class="btn btn-primary btn-sm" data-dismiss="modal">Não</button>
        	    <button type="submit" id="confirm-dialog-yes" class="btn btn-success btn-sm">Sim</button>
            </div>
        </div>
    </div>
</div>

BescheLab/layout/templates/delete_dialog.html
<div class="modal fade" id="deletedlg" tabindex="-1" role="dialog" aria-labelledby="">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
          
                <h4 class="modal-title">{{ dialog_message }}</h4>
            </div>
      
            <div class="modal-body">
                Esta operação não pode ser desfeita e em alguns casos ocasiona exclusão de outras informações.
            </div>
      
            <div class="modal-footer">
                <form action="" method="POST">{% csrf_token %}
            	    <button type="button" class="btn btn-primary btn-sm" data-dismiss="modal">Não</button>
            	    <button type="submit" class="btn btn-success btn-sm">Sim</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
$(function() {
    $("#delete-link").click(function(e) {
        href = $(this).data("href")
        $("#deletedlg form").attr("action", href)
        $("#deletedlg").modal()
    })
})
</script>

BescheLab/layout/templates/layout-base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <title>Besche Lab</title>

        <!-- JQuery -->
        <script src="{% static 'vendors/js/jquery.min.js' %}"></script>
        <!-- pace -->
        <script src="{% static 'vendors/js/pace/pace.min.js' %}"></script>
        <!-- Bootstrap -->
        <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
        <!-- NProgress -->
        <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
        <!-- iCheck -->
        <link href="{% static 'vendors/iCheck/skins/flat/green.css' %}" rel="stylesheet">
        <!-- bootstrap-progressbar -->
        <link href="{% static 'vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet">
        <!-- bootstrap-daterangepicker -->
        <link href="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.css' %}" rel="stylesheet">
        <link href="{% static 'vendors/switchery/dist/switchery.min.css' %}" rel="stylesheet">
        <link href="{% static 'vendors/switchery/dist/switchery.css' %}" rel="stylesheet">
        <!-- Custom Theme Style -->
        <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
        <!-- Select2 -->
        <link href="{% static 'vendors/select2/dist/css/select2.min.css' %}" rel="stylesheet">
        <!-- Switchery -->
        <link href="{% static 'vendors/switchery/dist/switchery.min.css' %}" rel="stylesheet">
        <!-- Tabela Responsiva -->
        <link href="{% static 'vendors/js/datatables/jquery.dataTables.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'vendors/js/datatables/buttons.bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'vendors/js/datatables/fixedHeader.bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'vendors/js/datatables/responsive.bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'vendors/js/datatables/scroller.bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'css/rowlink.css' %}" rel="stylesheet" type="text/css" />
        {{ form.media.css }}
        {% block extrahead %}{% endblock %}
    </head>

    <body class="nav-md">
        <div class="container body">
            <div class="main_container">
                <div class="col-md-3 left_col">
                    <div class="left_col scroll-view">
                        <div class="navbar nav_title" style="border: 0;">
                            <a href="{% url 'index' %}" class="site_title">
                                <i class="fa fa-flask"></i> <span>Besche Lab</span>
                            </a>
                        </div>

                        <div class="clearfix"></div>

                        <!--div class="profile clearfix">
                            <div class="profile_pic">
                                <img src="{%static 'images/img.jpg' %}" alt="..." class="img-circle profile_img">
                            </div>
                            <div class="profile_info">
                                <span>Bem Vindo(a),</span>
                                <h2>{{ request.user.get_short_name }}</h2>
                            </div>
                        </div-->
                        <br>
                        <!-- sidebar menu -->
                        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                            {% block sidebar_menu %}{% endblock %}
                        </div>
                        <!-- /sidebar menu -->
                    </div>
                </div>

                <!-- top navigation -->
                <div class="top_nav">
                    <div class="nav_menu">
                        <nav>
                            <div class="nav toggle">
                                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                            </div>
                            <ul class="nav navbar-nav navbar-right">
                                <li class=""><a href="javascript:;"
                                    class="user-profile dropdown-toggle" data-toggle="dropdown"
                                    aria-expanded="false"> <img
                                        src="{%static 'images/img.jpg' %}" alt="">
                                        {{ request.user }}
                                        <span class=" fa fa-angle-down"></span>
                                </a>
                                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                                        {% if perms.pessoa.change_usuario %}
                                        <li><a href="{% url 'configuracoes' %}">
                                            Configurações
                                        </a></li>
                                        {% endif %}

                                        <li><a href="#">
                                            Ajuda
                                        </a></li>
                                        
                                        <li><a href="{% url 'logout' %}">
                                            <i class="fa fa-sign-out pull-right"></i> Sair
                                        </a></li>
                                    </ul>
                                </li>
                                <li role="presentation" class="dropdown">
                                    <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                                        <i class="fa fa-bell-o"></i>
                                        {% if exames_pendentes.count > 0 or pagamentos_atrasados.count > 0 %}
                                        <span class="badge bg-red">
                                            {{ exames_pendentes.count|add:pagamentos_atrasados.count }}
                                        </span>
                                        {% endif %}
                                    </a>
                                    <ul id="notifications" class="dropdown-menu list-unstyled msg_list">
                                        <li class="title">Coletas não realizadas</li>
                                        {% for exame in exames_pendentes %}
                                        <li>
                                            <a href="{% url 'exame_marcado_editar' exame.pk %}">
                                                {{ exame.paciente.nome }}<br>
                                                Data: {{ exame.data }}
                                            </a>
                                        </li>
                                        {% empty %}
                                        <li>Nenhuma coleta não realizada</a></li>
                                        {% endfor %}
                                        <li class="title">Pagamentos atrasados</li>
                                        {% for pagamento in pagamentos_atrasados %}
                                        <li>
                                            <a href="{% url 'lancamento_detalhar' pagamento.lancamento_id %}">
                                                {{ pagamento.valor }}<br>
                                                Data: {{ pagamento.data }}
                                            </a>
                                        </li>
                                        {% empty %}
                                        <li>Nenhum pagamento atrasado</li>
                                        {% endfor %}
                                    </ul>
                                </li>
                                <li role="presentation" class="dropdown">
                                    {% if pontos_coleta.count > 1 or perms.pontos_coleta.change_pontocoleta %}
                                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                        {{ request.ponto_coleta }} <span class=" fa fa-angle-down"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        {% for ponto in pontos_coleta %}
                                        <li><a href="{% url 'pontos_coleta:selecionar' ponto.pk %}"><span>{{ ponto }}</span></a></li>
                                        {% endfor %}
                                    </ul>
                                    {% else %}
                                    <a href="javascript:;">
                                        {{ request.ponto_coleta }}
                                    </a>
                                    {% endif %}
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <!-- /top navigation -->

                <!-- page content -->
                <div class="right_col" role="main">
                    <div class="">
                    {% block conteudo %} 
                    {% endblock %}
                    </div>
                </div>
                <!-- /page content -->
                <!-- footer content -->
                <footer>
                    <div class="pull-right">
                        Desenvolvido por 
                        <a href="http://www.besche.com.br" target="_blank"><b>Besche Tecnologia</b></a>
                    </div>
                    <div class="clearfix"></div>
                </footer>
                <!-- /footer content -->
            </div>
        </div>

        <!-- Bootstrap -->
        <script src="{% static 'vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
        <!-- FastClick -->
        <script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
        <!-- NProgress -->
        <script src="{% static 'vendors/nprogress/nprogress.js' %}"></script>
        <!-- bootstrap-progressbar -->
        <script src="{% static 'vendors/bootstrap-progressbar/bootstrap-progressbar.min.js' %}"></script>
        <!-- iCheck -->
        <script src="{% static 'vendors/iCheck/icheck.min.js' %}"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="{% static 'vendors/moment/min/moment.min.js' %}"></script>
        <script src="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
        <script src="{% static 'vendors/jquery.hotkeys/jquery.hotkeys.js' %}"></script>
        <script src="{% static 'vendors/google-code-prettify/src/prettify.js' %}"></script>
        <!-- Switchery -->
        <script src="{% static 'vendors/switchery/dist/switchery.min.js' %}"></script>
        <!-- Autosize -->
        <script src="{% static 'vendors/autosize/dist/autosize.min.js' %}"></script>

        <script src="{% static 'vendors/datatables.net/js/jquery.dataTables.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js' %}"></script>
        <script src="{% static 'vendors/datatables.net-scroller/js/dataTables.scroller.min.js' %}"></script>
        <!-- Custom Theme Scripts -->
        <script src="{% static 'build/js/custom.min.js' %}"></script>
        <script src="{% static 'js/rowlink.js' %}"></script>

        <!-- Autosize -->
        <script>
          $(document).ready(function() {
            autosize($('.resizable_textarea'));
          });
        </script>
        <!-- /Autosize -->
{{ form.media.js }}
{% block extrascript %}{% endblock %}
    </body>
</html>

BescheLab/layout/templates/layout-config.html
{% extends 'layout-base.html' %}
{% block sidebar_menu %}
<!-- menu section -->
<div class="menu_section">
    <h3>Geral</h3>
    <ul class="nav side-menu">
        <li>
            <a href="{% url 'index' %}"><i class="fa fa-chevron-left"></i> Voltar </a>
        </li>
    </ul>
</div>
<!-- /menu section -->
<div class="menu_section">
    <h3>Configurações</h3>
    <ul class="nav side-menu">
        <li><a href="{% url 'configuracoes' %}"><i class="fa fa-cogs fa-lg"></i> Início </a></li>
        {% if perms.pessoa.change_usuario %}
        <li>
            <a><i class="fa fa-user fa-lg"></i> Usuário <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
                <li><a href="{% url 'usuario_adicionar' %}">Adicionar</a></li>
                <li><a href="{% url 'usuario_listar' %}">Lista</a></li>
            </ul>
        </li>
        {% endif %}
        
        {% if perms.pessoa.change_fornecedor %}
        <li>
            <a><i class="fa fa-industry fa-lg"></i> Fornecedor <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
                <li><a href="{% url 'fornecedor_adicionar' %}">Adicionar</a></li>
                <li><a href="{% url 'fornecedor_listar' %}">Lista</a></li>
            </ul>
        </li>
        {% endif %}

        {% if perms.auth.change_group %}
        <li>
            <a href="{% url 'grupo_listar' %}"><i class="fa fa-exclamation-triangle fa-lg"></i> Permissões </a>
        </li>
        {% endif %}
        
        {% if perms.laboratorio.change_exame %}
        <li>
            <a><i class="fa fa-clipboard fa-lg"></i> Exame <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
                <li><a href="{% url 'exame_adicionar' %}">Adicionar</a></li>
                <li><a href="{% url 'exame_listar' %}">Lista</a></li>
            </ul>
        </li>
        {% endif %}
        
        {% if perms.pontos_coleta.change_pontocoleta %}
        <li>
            <a><i class="fa fa-building fa-lg"></i> Ponto de Coleta <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
                <li><a href="{% url 'pontos_coleta:adicionar' %}">Adicionar</a></li>
                <li><a href="{% url 'pontos_coleta:listar' %}">Lista</a></li>
            </ul>
        </li>
        {% endif %}
    </ul>
</div>
<!--/menu section-->
{% endblock %}

BescheLab/layout/templates/relatorio-acoes.html
{% extends 'layout.html' %}
{% block conteudo %}
<div class="page-title">
    <div class="title_left">
        <h3>Auditoria do sistema</h3>
    </div>
</div>
<div class="clearfix"></div>
<div class="x_panel">
    <div class="x_title">
        <h2>Log Ações
            <small>
                Relatório de ações realizadas dentro do sistema.
            </small>
        </h2>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Usuário</th>
                    <th>Ação</th>
                    <th>Alteração</th>
                    <th>Data/Hora</th>
                    <th>IP</th>
                </tr>
            </thead>
            <tbody>
            {% for entry in log %}
                <tr>
                    <td>{{ entry.actor }}</td>
                    <td>
                        {% if entry.action == 0 %}Adicionado
                        {% elif entry.action == 1 %}Modificado
                        {% elif entry.action == 2 %}Apagado{% endif %}
                    </td>
                    <td>{{ entry.object_repr }}</td>
                    <td>{{ entry.timestamp }}</td>
                    <td>{{ entry.remote_addr }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}