BescheLab/pessoa/urls.py
from django.conf.urls import url
from .views import pessoa, fornecedor, usuario, grupo


urlpatterns = [
    url(r'^usuario/$', usuario.listar,
        name='usuario_listar'),
    url(r'^usuario/adicionar$', usuario.adicionar,
        name='usuario_adicionar'),
    url(r'^usuario/(?P<id>\d+)/editar$', usuario.editar,
        name='usuario_editar'),
    url(r'^usuario/(?P<pk>\d+)/apagar$', usuario.apagar,
        name='usuario_apagar'),
    url(r'^usuario/(?P<id>\d+)/definir_senha$', usuario.definir_senha,
        name='usuario_definir_senha'),

    url(r'^paciente/adicionar$', pessoa.adicionar,
        name='pessoa_adicionar'),
    url(r'^paciente/(?P<id>\d+)/editar$', pessoa.editar,
        name='pessoa_editar'),
    url(r'^paciente/(?P<id>\d+)/apagar$', pessoa.apagar,
        name='pessoa_apagar'),
    url(r'^pacientes$', pessoa.listar,
        name='pessoa_listar'),

    url(r'^fornecedor/adicionar$', fornecedor.adicionar,
        name='fornecedor_adicionar'),
    url(r'^fornecedor/(?P<id>\d+)/editar$', fornecedor.editar,
        name='fornecedor_editar'),
    url(r'^fornecedor/(?P<id>\d+)/apagar$', fornecedor.apagar,
        name='fornecedor_apagar'),
    url(r'^fornecedor/listar$', fornecedor.listar,
        name='fornecedor_listar'),

    url(r'^grupos/(?P<id>\d+)/editar$', grupo.editar,
        name='grupo_editar'),
    url(r'^grupos$', grupo.listar,
        name='grupo_listar'),
]

BescheLab/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^login', login, name='login'),
    url(r'^logout', logout_then_login, name='logout'),
    url(r'^table/', include('table.urls')),
    url(r'^pontos_coleta/', include('BescheLab.pontos_coleta.urls',
                                    namespace='pontos_coleta')),
    url(r'', include('BescheLab.layout.urls')),
    url(r'^pessoa/', include('BescheLab.pessoa.urls')),
    url(r'^financeiro/', include('BescheLab.financeiro.urls')),
    url(r'^laboratorio/', include('BescheLab.laboratorio.urls')),
]

BescheLab/pessoa/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.utils.encoding import python_2_unicode_compatible
from djchoices import DjangoChoices, ChoiceItem
from django.utils.timezone import now
from auditlog.registry import auditlog
from ..pontos_coleta.models import PontoColeta


class UsuarioManager(BaseUserManager):
    def create_user(self, login, password=None):
        """
        Cria e salva usuário a partir de login e senha
        """
        if not login:
            raise ValueError('Usuário deve possuir login')

        user = self.model(login=login)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, login, password=None):
        """
        Cria e salva super usuário a partir de login e senha
        """
        user = self.create_user(login, password=password)
        user.tipo = Usuario.Tipos.administrador
        user.save(using=self._db)
        return user


class PacienteManager(models.Manager):
    def get_queryset(self):
        return super(PacienteManager, self).get_queryset().filter(tipo='p')


class FornecedorManager(models.Manager):
    def get_queryset(self):
        return super(FornecedorManager, self).get_queryset().filter(tipo='f')


@python_2_unicode_compatible
class UF(models.Model):
    nome = models.CharField(max_length=100, unique=True)
    sigla = models.CharField(max_length=2, unique=True)

    def __str__(self):
        return '%s, %s' % (self.nome, self.sigla)


@python_2_unicode_compatible
class Municipio(models.Model):
    nome = models.CharField(max_length=100)
    uf = models.ForeignKey(UF, related_name='municipios')

    def __str__(self):
        return '%s, %s' % (self.nome, self.uf.sigla)


@python_2_unicode_compatible
class Pessoa(models.Model):
    class Sexos(DjangoChoices):
        masculino = ChoiceItem(1, 'Masculino')
        feminino = ChoiceItem(2, 'Feminino')

    nome = models.CharField(max_length=50)
    tipo = models.CharField(max_length=1, default='p', editable=False)
    telefone = models.CharField(max_length=12, null=True)
    email = models.EmailField('e-mail', max_length=50, blank=True, null=True)
    # Pessoa fisica
    cpf_cnpj = models.CharField('CPF/CPNJ', max_length=18, blank=True,
                                null=True)
    cns = models.CharField('CNS', max_length=15, blank=True, null=True)
    data_nascimento = models.DateField('Nascimento', blank=True, null=True)
    sexo = models.IntegerField('sexo', choices=Sexos.choices,
                               blank=True, null=True)
    # Endereço
    logradouro = models.CharField(max_length=50, null=True)
    numero = models.CharField('Número', max_length=10, null=True)
    complemento = models.CharField(max_length=50, blank=True, null=True)
    bairro = models.CharField(max_length=50, null=True)
    municipio = models.ForeignKey(Municipio, null=True)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Pessoa'
        default_permissions = []


class Paciente(Pessoa):
    objects = PacienteManager()

    def save(self, *kargs, **kwargs):
        self.tipo = 'p'
        return super(Paciente, self).save(*kargs, **kwargs)

    class Meta:
        proxy = True
        default_permissions = []
        permissions = (
            ('change_paciente', "Cadastrar paciente"),
            ('delete_paciente', "Excluir paciente"),
        )


class Fornecedor(Pessoa):
    objects = FornecedorManager()

    def save(self, *kargs, **kwargs):
        self.tipo = 'f'
        return super(Fornecedor, self).save(*kargs, **kwargs)

    class Meta:
        proxy = True
        default_permissions = []
        permissions = (
            ('change_fornecedor', "Cadastrar fornecedor"),
            ('delete_fornecedor', "Excluir fornecedor"),
        )


@python_2_unicode_compatible
class Usuario(AbstractBaseUser, PermissionsMixin):
    class Tipos(DjangoChoices):
        administrador = ChoiceItem(1, 'Administrador')
        gerente = ChoiceItem(2, 'Gerente')
        atentente = ChoiceItem(3, 'Atendente')
        analista = ChoiceItem(4, 'Analista')

    pessoa = models.OneToOneField(Pessoa, null=True, on_delete=models.CASCADE)
    login = models.CharField(max_length=20, unique=True)
    cbo = models.IntegerField('CBO', blank=True, null=True)
    n_conselho = models.IntegerField('Conselho de Classe',
                                     blank=True, null=True)
    admissao = models.DateField(default=now)
    ativo = models.BooleanField(default=True)
    tipo = models.IntegerField(choices=Tipos.choices, default=Tipos.atentente)
    pontos_coleta = models.ManyToManyField(
        PontoColeta, related_name='usuarios', verbose_name='ponto de coleta')

    objects = UsuarioManager()
    USERNAME_FIELD = 'login'

    def __str__(self):
        return self.get_short_name()

    @property
    def is_active(self):
        return self.ativo

    class Meta:
        verbose_name = 'Usuário'
        default_permissions = []
        permissions = (
            ('change_usuario', "Cadastrar"),
            ('log_acoes', "Relatorio de ações"),
        )

    # Para funcionamento correto do admin
    # <admin>
    @property
    def is_staff(self):
        return self.is_superuser

    @property
    def is_superuser(self):
        return self.tipo == Usuario.Tipos.administrador

    def get_short_name(self):
        if self.pessoa:
            return self.pessoa.nome.split(' ')[0]
        else:
            return self.login

    def get_full_name(self):
        if self.pessoa:
            return self.pessoa.nome
        else:
            return self.login
    # </admin>


auditlog.register(Paciente)
auditlog.register(Fornecedor)
auditlog.register(Usuario)

BescheLab/pessoa/views/fornecedor.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required, permission_required
from ..models import Fornecedor
from ..forms import FornecedorForm
from ..tables import FornecedorTable


@login_required
@permission_required('pessoa.change_fornecedor', raise_exception=True)
def adicionar(request):
    if request.method == 'POST':
        form = FornecedorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('fornecedor_listar'))
    else:
        form = FornecedorForm()
    return render(request, 'pessoa/fornecedor/form.html', {'form': form})


@login_required
@permission_required('pessoa.change_fornecedor', raise_exception=True)
def editar(request, id):
    fornecedor = Fornecedor.objects.get(id=id)

    if request.method == 'POST':
        form = FornecedorForm(request.POST, instance=fornecedor)
        if form.is_valid():
            form.save()
            return redirect(reverse('fornecedor_listar'))
    else:
        form = FornecedorForm(instance=fornecedor)
    return render(request, 'pessoa/fornecedor/form.html',
                  {'form': form, 'object': fornecedor})


@login_required
@permission_required('pessoa.delete_fornecedor', raise_exception=True)
def apagar(request, id):
    if request.method == 'POST':
        fornecedor = Fornecedor.objects.get(id=id)
        fornecedor.delete()
    return redirect(reverse('fornecedor_listar'))


@login_required
@permission_required('pessoa.change_fornecedor', raise_exception=True)
def listar(request):
    fornecedores = Fornecedor.objects.all()
    table = FornecedorTable()
    return render(request, 'pessoa/fornecedor/listar.html',
                  {'table': table, 'fornecedors': fornecedores})

BescheLab/pessoa/views/grupo.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import Group
from ..forms import GrupoForm


@login_required()
@permission_required('auth.change_group', raise_exception=True)
def listar(request):
    grupos = Group.objects.all()
    return render(request, 'pessoa/grupo/listar.html', {'grupos': grupos})


@login_required()
@permission_required('auth.change_group', raise_exception=True)
def editar(request, id):
    grupo = Group.objects.get(pk=id)
    if request.method == 'POST':
        form = GrupoForm(request.POST, instance=grupo)
        if form.is_valid():
            form.save()
            return redirect(reverse('grupo_listar'))
    else:
        form = GrupoForm(instance=grupo)

    return render(request, 'pessoa/grupo/form.html',
                  {'object': grupo, 'form': form})

BescheLab/pessoa/views/pessoa.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required, permission_required
from ..models import Paciente
from ..forms import PessoaForm
from ..tables import PacienteTable


@login_required
@permission_required('pessoa.change_paciente', raise_exception=True)
def adicionar(request):
    if request.method == 'POST':
        form = PessoaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('pessoa_listar'))
    else:
        form = PessoaForm()
    return render(request, 'pessoa/paciente/form.html', {'form': form})


@login_required
@permission_required('pessoa.change_paciente', raise_exception=True)
def editar(request, id):
    pessoa = Paciente.objects.get(id=id)

    if request.method == 'POST':
        form = PessoaForm(request.POST, instance=pessoa)
        if form.is_valid():
            form.save()
            return redirect(reverse('pessoa_listar'))
    else:
        form = PessoaForm(instance=pessoa)
    return render(request, 'pessoa/paciente/form.html',
                  {'form': form, 'object': pessoa})


@login_required
@permission_required('pessoa.delete_paciente', raise_exception=True)
def apagar(request, id):
    if request.method == 'POST':
        pessoa = Paciente.objects.get(id=id)
        pessoa.delete()
    return redirect(reverse('pessoa_listar'))


@login_required
@permission_required('pessoa.change_paciente', raise_exception=True)
def listar(request):
    pessoas = Paciente.objects.all()
    table = PacienteTable()
    return render(request, 'pessoa/paciente/listar.html',
                  {'table': table, 'pessoas': pessoas})

BescheLab/pessoa/views/usuario.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth.forms import AdminPasswordChangeForm
from django.contrib.auth.decorators import login_required, permission_required
from ..models import Usuario
from ..forms import UsuarioForm
from ..tables import UsuarioTable


@login_required
@permission_required('pessoa.change_usuario', raise_exception=True)
def listar(request):
    table = UsuarioTable()
    usuarios = Usuario.objects.all()
    return render(request, 'pessoa/usuario/listar.html',
                  {'table': table, 'usuarios': usuarios})


@login_required
@permission_required('pessoa.change_usuario', raise_exception=True)
def adicionar(request):
    if request.method == 'POST':
        form = UsuarioForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('usuario_listar'))
    else:
        form = UsuarioForm()

    return render(request, 'pessoa/usuario/form.html', {'form': form})


@login_required
@permission_required('pessoa.change_usuario', raise_exception=True)
def editar(request, id):
    usuario = Usuario.objects.get(pk=id)
    if request.method == 'POST':
        form = UsuarioForm(request.POST, instance=usuario)
        if form.is_valid():
            form.save()
            return redirect(reverse('usuario_listar'))
    else:
        form = UsuarioForm(instance=usuario)

    return render(request, 'pessoa/usuario/form.html',
                  {'object': usuario, 'form': form})


@login_required
@permission_required('pessoa.change_usuario', raise_exception=True)
def definir_senha(request, id):
    usuario = Usuario.objects.get(pk=id)
    if request.method == 'POST':
        form = AdminPasswordChangeForm(usuario, request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('usuario_listar'))
    else:
        form = AdminPasswordChangeForm(usuario)

    return render(request, 'pessoa/usuario/form.html',
                  {'object': usuario, 'form': form})


@login_required
@permission_required('pessoa.change_usuario', raise_exception=True)
def apagar(request, pk):
    if request.method == 'POST':
        exame = Usuario.objects.get(pk=pk)
        exame.delete()
    return redirect(reverse('usuario_listar'))

BescheLab/pessoa/templates/pessoa/paciente/form.html
{% extends 'layout.html' %}
{% load bootstrap3 %}
{% block conteudo %}
<div class="page-title">
    <div class="title_left">
        <h3>Pessoa</h3>
    </div>
</div>
<div class="clearfix"></div>
<div class="x_panel">
    <div class="x_title">
        <h2>{% if object %}Editar
            <small>
                Veja detalhes e/ou altere informações de uma pessoa.
            </small>
            {% else %}Adicionar
            <small>
                Adicione uma nova pessoa.
            </small>
            {% endif %}
        </h2>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">
        <form novalidate class="form-horizontal form-label-left" method="POST">{% csrf_token %}
            {% bootstrap_form_errors form type='non_fields' %}
            {% bootstrap_field form.nome layout='horizontal' field_class='col-xs-12 col-sm-10 col-md-10' label_class='col-xs-12 col-sm-2 col-md-2' %}
            <div class="form-group">
                {% bootstrap_field form.telefone field_class='col-xs-12 col-sm-4 col-md-4' label_class='col-xs-12 col-sm-2 col-md-2' form_group_class='' %}
                {% bootstrap_field form.email field_class='col-xs-12 col-sm-4 col-md-4' label_class='col-xs-12 col-sm-2 col-md-2' form_group_class='' %}
            </div>
            
            <div class="form-group">
                {% bootstrap_field form.cpf_cnpj field_class='col-xs-12 col-sm-4 col-md-4' label_class='col-xs-12 col-sm-2 col-md-2' form_group_class='' %}
                {% bootstrap_field form.cns field_class='col-xs-12 col-sm-4 col-md-4' label_class='col-xs-12 col-sm-2 col-md-2' form_group_class='' %}
            </div>
            
            <div class="form-group">
                {% bootstrap_field form.data_nascimento field_class='col-xs-12 col-sm-4 col-md-4' label_class='col-xs-12 col-sm-2 col-md-2' form_group_class='' %}
                <label class="col-xs-12 col-sm-2 col-md-2 control-label" for="id_idade">Idade</label>
                <div class="col-xs-12 col-sm-4 col-md-4">
                    <input class="form-control" id="id_idade" maxlength="3" name="idade" placeholder="Idade" type="text">
                </div>
            </div>
            <div class="form-group">
                {% bootstrap_field form.sexo field_class='col-xs-12 col-sm-4 col-md-4' label_class='col-xs-12 col-sm-2 col-md-2' form_group_class='' %}
            </div>

            <div class="divider-dashed"></div>

            <div class="form-group">
                {% bootstrap_field form.logradouro field_class='col-xs-12 col-sm-4 col-md-4' label_class='col-xs-12 col-sm-2 col-md-2' form_group_class='' %}
                {% bootstrap_field form.numero field_class='col-xs-12 col-sm-4 col-md-4' label_class='col-xs-12 col-sm-2 col-md-2' form_group_class='' %}
            </div>
            
            <div class="form-group">
                {% bootstrap_field form.complemento field_class='col-xs-12 col-sm-4 col-md-4' label_class='col-xs-12 col-sm-2 col-md-2' form_group_class='' %}
                {% bootstrap_field form.bairro field_class='col-xs-12 col-sm-4 col-md-4' label_class='col-xs-12 col-sm-2 col-md-2' form_group_class='' %}
            </div>
            
            <div class="form-group">
                {% bootstrap_field form.municipio field_class='col-xs-12 col-sm-4 col-md-4' label_class='col-xs-12 col-sm-2 col-md-2' form_group_class='' %}
            </div>
            
            <div class="ln_solid"></div>
            
            <div class="form-group">
                <div class="col-xs-12 col-sm-10 col-sm-offset-2 col-md-10 col-md-offset-2">
                    {% if object and perms.pessoa.delete_pessoa %}
                    <div class="pull-right">
                        <button type="button" data-href="{% url 'pessoa_apagar' object.pk %}" id="delete-link" class="btn btn-danger btn-sm">Excluir</button>
                    </div>
                    {% endif %}
                    {% if object %}
                    <a href="{% url 'pessoa_listar' %}">
                    {% else %}
                    <a href="{% url 'index' %}"> 
                    {% endif %}
                        <div class="btn btn-sm btn-primary">Voltar</div>
                    </a>
                    <button type="submit" class="btn btn-sm btn-success">Salvar</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block extrascript %}
<script type="text/javascript">
function data_nascimento_change(){
    ano_nascimento = $("#id_data_nascimento").val().split('/')[2]
    idade = new Date().getFullYear() - ano_nascimento
    $("#id_idade").val(idade)
}
$(document).ready(function() {
    $("#id_data_nascimento").change(data_nascimento_change)
    $("#id_idade").change(function() {
        idade = parseInt($(this).val())
        ano_nascimento = new Date().getFullYear() - idade
        $("#id_data_nascimento").val("01/01"+ano_nascimento)
    })
    data_nascimento_change()
})
</script>
{% if object %}
{% with dialog_message='Deseja realmente excluir este paciente?' %}
{% include 'delete_dialog.html' %}
{% endwith %}
{% endif %}
{% endblock %}

BescheLab/pessoa/templates/pessoa/paciente/listar.html
{% extends 'layout.html' %} 
{% load table_tags %}
{% block conteudo %}
<div class="page-title">
	<div class="title_left">
		<h3>Pessoa</h3>
	</div>
</div>

<div class="clearfix"></div>

<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>Lista 
					<small>
						Lista com todas as pessoas. Clique numa linha para ver detalhes ou editar as informações.
					</small>
				</h2>
				<div class="clearfix"></div>
			</div>

			<div class="x_content">
				<br>
				{% render_table table %}
			</div>
		</div>
	</div>
</div>
{% endblock%}