BescheLab/laboratorio/urls.py
from django.conf.urls import url
from .views import exame, exame_marcado


urlpatterns = [
    url(r'^exame/adicionar$', exame.adicionar,
        name='exame_adicionar'),
    url(r'^exame/editar/(?P<pk>\d+)$', exame.editar,
        name='exame_editar'),
    url(r'^exame/apagar/(?P<pk>\d+)$', exame.apagar,
        name='exame_apagar'),
    url(r'^exame/detalhar/(?P<pk>\d+)$', exame.detalhar,
        name='exame_detalhar'),
    url(r'^exame/listar$', exame.listar,
        name='exame_listar'),

    url(r'^exame_marcado/adicionar$', exame_marcado.adicionar,
        name='exame_marcado_adicionar'),
    url(r'^exame_marcado/editar/(?P<pk>\d+)$', exame_marcado.editar,
        name='exame_marcado_editar'),
    url(r'^exame_marcado/apagar/(?P<pk>\d+)$', exame_marcado.apagar,
        name='exame_marcado_apagar'),
    url(r'^exame_marcado/listar$', exame_marcado.listar,
        name='exame_marcado_listar'),
]

BescheLab/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^login', login, name='login'),
    url(r'^logout', logout_then_login, name='logout'),
    url(r'^table/', include('table.urls')),
    url(r'^pontos_coleta/', include('BescheLab.pontos_coleta.urls',
                                    namespace='pontos_coleta')),
    url(r'', include('BescheLab.layout.urls')),
    url(r'^pessoa/', include('BescheLab.pessoa.urls')),
    url(r'^financeiro/', include('BescheLab.financeiro.urls')),
    url(r'^laboratorio/', include('BescheLab.laboratorio.urls')),
]

BescheLab/laboratorio/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from auditlog.registry import auditlog
from ..pessoa.models import Pessoa
from ..pontos_coleta.models import PontoColeta


@python_2_unicode_compatible
class Exame(models.Model):
    tipo = models.CharField(max_length=250)
    codigo = models.CharField(max_length=10, null=True)
    valor = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return '%s (%s)' % (self.tipo, self.codigo)

    class Meta:
        ordering = ('tipo',)
        verbose_name = 'Tipo de exame'
        default_permissions = []
        permissions = (
            ('change_exame', 'Cadastrar'),
            ('delete_exame', 'Excluir'),
        )


@python_2_unicode_compatible
class ExameMarcado(models.Model):
    ponto_coleta = models.ForeignKey(PontoColeta, editable=False)
    exames = models.ManyToManyField(Exame, related_name='marcados')
    paciente = models.ForeignKey(Pessoa)
    data = models.DateField()
    feito = models.BooleanField('Coletado', default=False)

    def __str__(self):
        return 'Exames %s %s' % (self.paciente, self.data)

    class Meta:
        verbose_name = 'Marcação de exame'
        default_permissions = []
        permissions = (
            ('change_examemarcado', "Marcar e Remarcar"),
            ('realizar_examemarcado', "Realizar"),
            ('delete_examemarcado', "Excluir"),
        )


auditlog.register(Exame, include_fields=('valor',))
auditlog.register(ExameMarcado)

BescheLab/laboratorio/forms.py
from django import forms
from django_select2.forms import ModelSelect2Widget, ModelSelect2MultipleWidget
from django.forms.models import modelform_factory
from ..layout.forms import ReadOnlyFieldsMixin
from .models import ExameMarcado, Exame
from ..pessoa.models import Paciente

ExameForm = modelform_factory(Exame, fields=('tipo', 'valor'))


class ExameMarcadoForm(forms.ModelForm):
    class Meta:
        model = ExameMarcado
        fields = ('paciente', 'exames', 'data')
        widgets = {
            'data': forms.widgets.DateInput(attrs={'class': 'date-picker'}),
            'paciente': ModelSelect2Widget(queryset=Paciente.objects.all(),
                                           search_fields=['nome__icontains']),
            'exames': ModelSelect2MultipleWidget(
                model=Exame, search_fields=['tipo__icontains'])
        }

    class Media:
        js = ('js/date-picker.js',)


class EditarExameMarcadoForm(ReadOnlyFieldsMixin, ExameMarcadoForm):
    readonly_fields = ('paciente', 'exames')

    class Meta(ExameMarcadoForm.Meta):
        fields = ('paciente', 'exames', 'data', 'feito')

BescheLab/laboratorio/views/exame.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required, permission_required
from ..models import Exame
from ..forms import ExameForm
from ..tables import ExameTable


@login_required
@permission_required('laboratorio.change_exame', raise_exception=True)
def listar(request):
    table = ExameTable()
    exames = Exame.objects.all()
    return render(request, 'laboratorio/exame/listar.html',
                  {'table': table, 'exames': exames})


@login_required
@permission_required('laboratorio.change_exame', raise_exception=True)
def detalhar(request, pk):
    exame = Exame.objects.get(pk=pk)
    return render(request, 'laboratorio/exame/detalhar.html', {'exame': exame})


@login_required
@permission_required('laboratorio.change_exame', raise_exception=True)
def adicionar(request):
    if request.method == 'POST':
        form = ExameForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('exame_listar'))
    else:
        form = ExameForm()
    return render(request, 'laboratorio/exame/form.html', {'form': form})


@login_required
@permission_required('laboratorio.change_exame', raise_exception=True)
def editar(request, pk):
    exame = Exame.objects.get(pk=pk)
    if request.method == 'POST':
        form = ExameForm(request.POST, instance=exame)
        if form.is_valid():
            form.save()
            return redirect(reverse('exame_listar'))
    else:
        form = ExameForm(instance=exame)
    return render(request, 'laboratorio/exame/form.html',
                  {'form': form, 'object': exame})


@login_required
@permission_required('laboratorio.delete_exame', raise_exception=True)
def apagar(request, pk):
    if request.method == 'POST':
        exame = Exame.objects.get(pk=pk)
        exame.delete()
    return redirect(reverse('exame_listar'))

BescheLab/laboratorio/views/exame_marcado.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Sum
from formtools.wizard.views import SessionWizardView
from ...layout.decorators import any_permission_required
from ...financeiro.forms import LancamentoForm
from ..forms import ExameMarcadoForm, EditarExameMarcadoForm
from ..models import ExameMarcado, Exame
from ..tables import ExameMarcadoTable


def gerar_lancamento(exame_marcado):
    total = 0
    descricao = []
    if isinstance(exame_marcado, ExameMarcado):
        exames = exame_marcado.exames
        pessoa_id = exame_marcado.paciente_id
    else:
        exames = exame_marcado.get('exames')
        pessoa_id = exame_marcado.get('paciente')
    for exame in exames.all():
        total += exame.valor
        descricao.append('%s' % (exame))

    return {
        'valor': float(total),
        'descricao': '\n'.join(descricao),
        'pessoa': pessoa_id,
    }


@login_required
@any_permission_required('laboratorio.change_examemarcado',
                         'laboratorio.realizar_examemarcado')
def listar(request):
    exames = ExameMarcado.objects.filter(
        ponto_coleta=request.ponto_coleta, feito=False).order_by('data')
    table = ExameMarcadoTable(exames)
    return render(request, 'laboratorio/exame_marcado/listar.html',
                  {'table': table, 'exames': exames})


@login_required
@any_permission_required('laboratorio.change_examemarcado',
                         'laboratorio.realizar_examemarcado')
def editar(request, pk):
    exame = ExameMarcado.objects.get(pk=pk)
    if request.method == 'POST':
        form = EditarExameMarcadoForm(request.POST, instance=exame)
        if form.is_valid():
            form.save()
            return redirect(reverse('exame_marcado_listar'))
    else:
        readonly_fields = []
        if not request.user.has_perm('laboratorio.change_examemarcado'):
            readonly_fields.extend(('exames', 'data'))
        if not request.user.has_perm('laboratorio.realizar_examemarcado'):
            readonly_fields.append('feito')
        form = EditarExameMarcadoForm(readonly_fields=readonly_fields,
                                      instance=exame)
    return render(request, 'laboratorio/exame_marcado/form.html',
                  {'form': form, 'object': exame})


@login_required
@permission_required('laboratorio.delete_examemarcado', raise_exception=True)
def apagar(request, pk):
    if request.method == 'POST':
        exame = ExameMarcado.objects.get(pk=pk)
        exame.delete()
    return redirect(reverse('exame_marcado_listar'))


class AdicionarWizard(SessionWizardView):
    form_list = [
        ('exame', ExameMarcadoForm),
        ('pagamento', LancamentoForm)
    ]
    template_names = {
        'exame': 'laboratorio/exame_marcado/form.html',
        'pagamento': 'lancamento/adicionar.html'
    }
    condition_dict = {'pagamento': lambda w: w.requer_pagamento}
    requer_pagamento = True

    def calcula_pagamento(self, exames_ids):
        total = Exame.objects.filter(id__in=exames_ids).aggregate(
            total=Sum('valor'))['total']
        self.requer_pagamento = total > 0
        return self.requer_pagamento

    def get_template_names(self):
        return self.template_names[self.steps.current]

    def process_step(self, form):
        if self.steps.current == 'exame':
            self.calcula_pagamento(form.data.getlist('exame-exames'))
            lancamento = gerar_lancamento(form.cleaned_data)
            self.initial_dict['pagamento'] = lancamento
        return self.get_form_step_data(form)

    def done(self, form_list, **kwargs):
        if self.requer_pagamento:
            form_exame, form_pagamento = form_list
        else:
            form_exame, = form_list
        em = form_exame.save(commit=False)
        em.ponto_coleta = self.request.ponto_coleta
        em.save()
        form_exame.save_m2m()
        if self.requer_pagamento:
            pagamento = form_pagamento.save(commit=False)
            pagamento.ponto_coleta = self.request.ponto_coleta
            pagamento.tipo = 1
            pagamento.save()
        return redirect(reverse('exame_marcado_listar'))


adicionar = AdicionarWizard.as_view()

BescheLab/laboratorio/templates/laboratorio/exame_marcado/form.html
{% extends 'layout.html' %}
{% load bootstrap3 %}
{% block conteudo %}
<div class="page-title">
    <div class="title_left">
        <h3>Agenda</h3>
    </div>
</div>

<div class="clearfix"></div>

<div class="x_panel">
    <div class="x_title">
        <h2>{% if object %}Alterar
            <small>
                Veja detalhes e/ou altere informações de uma marcação de Coleta de Material para exame.    
            </small>
            {% else %}Marcar
            <small>
                Adicione uma nova marcação de Coleta de Material para exame.
            </small>
            {% endif %}
        </h2>
        <div class="clearfix"></div>
    </div>

    <div class="x_content">
        <br>
        <form novalidate class="form-horizontal form-label-left" method="POST">{% csrf_token %}
            {{ wizard.management_form }}
            {% bootstrap_form_errors form type='non_fields' %}
            {% for field in form %}
            {% bootstrap_field field layout='horizontal' field_class='col-xs-12 col-sm-10 col-md-10' label_class='col-xs-12 col-sm-2 col-md-2' %}
            {% endfor %}
            <div class="ln_solid"></div>
            
            <div class="form-group">
                <div class="col-xs-12 col-sm-10 col-sm-offset-2 col-md-10 col-md-offset-2">
                    {% if object and perms.laboratorio.delete_examemarcado %}
                    <div class="pull-right">
                        <button type="button" data-href="{% url 'exame_marcado_apagar' object.pk %}" id="delete-link" class="btn btn-danger btn-sm">Excluir</button>
                    </div>
                    {% endif %}
                    <a href="{% url 'index' %}">
                        <div class="btn btn-primary btn-sm">Voltar</div>
                    </a>
                    <button type="submit" class="btn btn-success btn-sm">Salvar</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block extrascript %}
<script type="text/javascript">
$("#id_data, #id_exame-data").daterangepicker({
    locale: daterangepicker_locale,
    singleDatePicker: true,
    showDropdowns: true,
    minDate: new Date()
})
</script>
{% if object %}
{% with dialog_message='Deseja realmente excluir esta marcação de exame?' %}
{% include 'delete_dialog.html' %}
{% endwith %}
{% else %}
<script type="text/javascript">
$("#id_paciente, #id_exame-paciente").on("change", function() {
    id = $(this).val()
    $.get("{% url 'movimento_pendentes' %}?paciente_id="+id, function(data) {
        if(data.pendencias > 0) {
            $("#alert-dialog").modal()
        }
    })
})
</script>
{% with dialog_message='Este paciente possui pendências de pagamento.' %}
{% include 'alert-dialog.html' %}
{% endwith %}
{% endif %}
{% endblock %}

BescheLab/laboratorio/templates/laboratorio/exame_marcado/listar.html
{% extends 'layout.html' %}
{% load table_tags %}
{% block conteudo %}
<div class="clearfix"></div>

<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>Agenda 
					<small>
						Lista com todas as Marcações de Exame. Clique numa linha para ver detalhes ou editar as informações.
					</small>
				</h2>

				<ul class="nav navbar-right panel_toolbox">
                	<li>
                		<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                	</li>
                </ul>

				<div class="clearfix"></div>
			</div>

			<div class="x_content">
				<br>
				{% render_table table %}
			</div>
		</div>
	</div>
</div>
{% endblock%}